""" An incomplete list of bad words found in english language """

__bad_words = {'bitchiness', 'bitchi', 'bitchyness', 'bitchy', 'sh!t', 'screwing', 'sexx', 'h0r', 'nigur', 'flikker',
               'knobz', 'sx', 'sluts', 'ass', 'packie', 'slut', 'pula', 'bitch', 'penas', 'buttwipe', 'dego', 'c0k',
               'lipshits', 'gook', 'scank', 'puta', 'phuck', 'phuk', 'mamhoon', 'nepesaurio', 'muie', 'mofo', 'jisim',
               'fagz', 'wank', 'queerz', 'amcik', 'slutz', 'assholes', 'pimmel', 'jiss', 'shitz', 'motherfucker',
               'cunt', 'sexxx', 'bassterds', 'pecker', 'masterbates', 'screw', 'jism', 'scheiss', 'dilld0', 'clits',
               'poop', 'mothafucker', 'buttpirate', '@$$', 'pr1c', 'nutsack', 'lesbo', 'motherfukah', 'masturbat',
               'fucking', 's.o.b.', 'kraut', 'fucks', 'ficken', 'faigs', 'nigger', 'cuntz', 'turd', 'merd', 'lezzian',
               'bitches', 'piss', 'shit', 'gays', 'oriface', 'muschi', 'dild0s', 'asshole', 'assmonkey', 'fuken',
               'testicle', 'fotze', 'fanny', 'shits', 'vagina', 'dupa', 'peinus', 'cum', 'wh0re', 'knulle', 'sh1tter',
               'packy', 'fukah', 'kurwa', 'kawk', 'kunt', 'w00se', 'ejakulate', 'masterbate', 'nazi', 'skanck',
               'shytty', 'retard', 'mothafuker', 'va1jina', 'vulva', 'faen', 'preteen', 'c0cks', 'kyrpa', 'kuntz',
               'ekrem', 'h0ar', 'dild0', 'g00k', 'boffing', 'h00r', 'masstrbate', 'qweir', 'faggit', 'orospu',
               'sonofabitch', 'fukkah', 'slutty', 'masochist', 'kuk', 'pule', 'rectum', 'jackoff', 'h0re', 'pussy',
               'bastardz', 'butthole', 'cntz', 'shitt', 'helvete', 'enema', 'foreskin', 'cock', 'fukk', 'schlong',
               'kike', 'dildos', 'xrated', 'fukin', 'fuckin', 'breasts', 'perse', 'shi+', 'ejackulate', 'assh0le',
               'ekto', 'whoar', 'pr1ck', 'masterbat', 'poonani', 'masterbat3', 'huevon', 'bch', 'dominatrics',
               'bastard', 'gaybor', 'dildo', 'azzhole', 'pimpis', 'basterdz', 'smut', 'crap', 'b1tch', 'arschloch',
               'bich', 'clit', 'fuck', 'asswipe', 'masterbaiter', 'hell', 'recktum', 'fart', 'dziwka', 'cipa',
               'muthafukah', 'vullva', 'pusse', 'xxx', 'sharmute', 'fucka', 'fatass', 'assface', 'shemale', 'sh1t',
               'kanker', 'fuchah', 'penis', 'motha', 'daygo', 'muthafukker', 'hui', 'faig', 'lesbian', 'bi7ch',
               'niiger', 'n1gr', 'nazis', 'guiena', 'wh00r', 'cawk', 'faggot', 'bullshit', 'kurac', 'penuus', 'nigga',
               'queer', 'cabron', 'puuker', 'knobs', 'knob', 'muthafuker', 'shitter', 'fagit', 'jerkoff', 'fags',
               'boiolas', 'basterds', 'cawks', 'queers', 'skrib', 'orafis', 'picka', 'scrotum', 'damn', 'btch',
               'shitty', 'carpetmuncher', 'kusi', 'fucker', 'cocks', 'l3i+ch', 'masturbate', 'qweers', 'niggas',
               'kunts', 'sh1tz', 'muthafukkah', 'bastards', 'dike', 'shiz', 'phuc', 'fukken', 'dominatrix', 'tits',
               'dilld0s', 'kuksuger', 'peeenus', 'skank', 'schmuck', 'teez', 'peeenusss', 'mouliewop', 'asholes',
               'shity', 'gayboy', 'whore', 'puto', 'nastt', 'l3itch', 'tit', 'fitt', 'schlampe', 'paky', 'massterbait',
               'cockhead', 'klootzak', 'arse', 'mutha', 'c0ck', 'enculer', 'skankee', 'fanculo', 'semen', 'fcuk',
               'boobs', 'fag1t', 'fu', 'fukker', 'vag1na', 'feg', 'vajina', 'h4x0r', 'motherfukker', 'anus', 'schaffer',
               'mothafukker', 'gaygirl', 'fux0r', 'paska', 'dominatricks', 'fukka', 'w0p', 'sharmuta', 'qweerz', 'fag',
               'bollock', 'fagg1t', 'chink', 'flipping', 'orifice', 'nasty', 'sexy', 'niigr', 'futkretzn', 'vaj1na',
               'feces', 'penus', 'ahole', 'ash0les', 'masstrbait', 'dyke', 'sh1ts', 'hoore', 'andskota', 'shyte',
               'jizm', 'orifiss', 'penisbreath', 'cazzo', 'pakie', 'pierdol', 'polack', 'lipshitz', 'assholz', 'dick',
               'pillu', 'skanks', 'skanky', 'orgasm', 'phuker', 'testical', 'dirsa', 'skankey', 'poontsee', 'japs',
               'chuj', 'peenus', 'hoer', 'hoor', 'orgasim', 'ayir', 'shipal', 'phukker', 'pizda', 'ash0le', 'pr0n',
               'p0rn', 'buceta', 'monkleigh', 'blowjob', 'jizz', 'fukkin', 'puuke', 'masokist', 'cocksucker', 'shyt',
               'pen1s', 'hore', 'injun', 'hells', 'faget', 'assh0lez', 'queef', 'muthafucker', 'polac', 'b00bs',
               'fudgepacker', 'rautenberg', 'goddamned', 'mibun', 'porn', 'orgasum', 'vagiina', 'motherfuker', 'hoar',
               'packi', 'sht', 'gayz', 'polak', 'assrammer', 'paki', 'chraa', 'biatch', 'sh1ter', 'fuk', 'gay', 'd4mn',
               'jap', 'motherfukkah', 'teets', 'fuker', 'cnts', 'pr1k', 'sadist', 'qahbeh', 'b17ch', 'honkey',
               'mothafukkah', 'mulkku', 'felcher', 'cunts', 'titt', 'pussee'}


def get_bad_words():
    return __bad_words
